import React, { createContext, useState } from 'react';

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('hi'); // Default to Hindi

  const translations = {
    en: {
      tagline: 'Your Health Companion',
      selectLanguage: 'Select Language',
      symptomCheck: 'Check Symptoms',
      symptomCheckDesc: 'Describe your symptoms and get guidance',
      findPHC: 'Find Health Center',
      findPHCDesc: 'Locate nearby healthcare facilities',
      emergencyHelp: 'Emergency Help',
      emergencyHelpDesc: 'Quick access to emergency services',
      disclaimer: '⚠️ This is not a replacement for professional medical advice. Always consult a doctor for serious symptoms.',
      greeting: 'Namaste! I am Arogya Sathi, your health companion. How can I help you today?',
      typeOrSpeak: 'Type or speak your symptoms...',
      analyzing: 'Analyzing',
      urgentAttention: 'Urgent Attention Required',
      seekImmediateHelp: 'Please seek immediate medical attention at the nearest health center or call emergency services.',
      nearbyHealthCenters: 'Nearby Health Centers',
      distance: 'Distance',
      call: 'Call',
      getDirections: 'Get Directions',
    },
    hi: {
      tagline: 'आपका स्वास्थ्य साथी',
      selectLanguage: 'भाषा चुनें',
      symptomCheck: 'लक्षण जांचें',
      symptomCheckDesc: 'अपने लक्षणों का वर्णन करें और मार्गदर्शन प्राप्त करें',
      findPHC: 'स्वास्थ्य केंद्र खोजें',
      findPHCDesc: 'नजदीकी स्वास्थ्य सुविधाओं का पता लगाएं',
      emergencyHelp: 'आपातकालीन सहायता',
      emergencyHelpDesc: 'आपातकालीन सेवाओं तक त्वरित पहुंच',
      disclaimer: '⚠️ यह पेशेवर चिकित्सा सलाह का विकल्प नहीं है। गंभीर लक्षणों के लिए हमेशा डॉक्टर से परामर्श लें।',
      greeting: 'नमस्ते! मैं आरोग्य साथी हूं, आपका स्वास्थ्य साथी। आज मैं आपकी कैसे मदद कर सकता हूं?',
      typeOrSpeak: 'अपने लक्षण टाइप करें या बोलें...',
      analyzing: 'विश्लेषण कर रहे हैं',
      urgentAttention: 'तत्काल ध्यान आवश्यक',
      seekImmediateHelp: 'कृपया निकटतम स्वास्थ्य केंद्र पर तुरंत चिकित्सा सहायता लें या आपातकालीन सेवाओं को कॉल करें।',
      nearbyHealthCenters: 'नजदीकी स्वास्थ्य केंद्र',
      distance: 'दूरी',
      call: 'कॉल करें',
      getDirections: 'दिशा-निर्देश प्राप्त करें',
    },
    ta: {
      tagline: 'உங்கள் சுகாதார துணை',
      selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
      symptomCheck: 'அறிகுறிகளைச் சரிபார்க்கவும்',
      symptomCheckDesc: 'உங்கள் அறிகுறிகளை விவரிக்கவும் மற்றும் வழிகாட்டுதலைப் பெறவும்',
      findPHC: 'சுகாதார மையத்தைக் கண்டறியவும்',
      findPHCDesc: 'அருகிலுள்ள சுகாதார வசதிகளைக் கண்டறியவும்',
      emergencyHelp: 'அவசர உதவி',
      emergencyHelpDesc: 'அவசர சேவைகளுக்கு விரைவான அணுகல்',
      disclaimer: '⚠️ இது தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாக இல்லை. தீவிர அறிகுறிகளுக்கு எப்போதும் மருத்துவரை அணுகவும்.',
      greeting: 'வணக்கம்! நான் ஆரோக்ய சாத்தி, உங்கள் சுகாதார துணை. இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?',
      typeOrSpeak: 'உங்கள் அறிகுறிகளை தட்டச்சு செய்யவும் அல்லது பேசவும்...',
      analyzing: 'பகுப்பாய்வு செய்கிறது',
      urgentAttention: 'அவசர கவனம் தேவை',
      seekImmediateHelp: 'அருகிலுள்ள சுகாதார மையத்தில் உடனடியாக மருத்துவ உதவியைப் பெறவும் அல்லது அவசர சேவைகளை அழைக்கவும்.',
      nearbyHealthCenters: 'அருகிலுள்ள சுகாதார மையங்கள்',
      distance: 'தூரம்',
      call: 'அழைக்கவும்',
      getDirections: 'வழிகளைப் பெறவும்',
    },
    te: {
      tagline: 'మీ ఆరోగ్య సహాయకుడు',
      selectLanguage: 'భాషను ఎంచుకోండి',
      symptomCheck: 'లక్షణాలను తనిఖీ చేయండి',
      symptomCheckDesc: 'మీ లక్షణాలను వివరించండి మరియు మార్గదర్శకత్వం పొందండి',
      findPHC: 'ఆరోగ్య కేంద్రాన్ని కనుగొనండి',
      findPHCDesc: 'సమీపంలోని ఆరోగ్య సౌకర్యాలను గుర్తించండి',
      emergencyHelp: 'అత్యవసర సహాయం',
      emergencyHelpDesc: 'అత్యవసర సేవలకు త్వరిత ప్రాప్యత',
      disclaimer: '⚠️ ఇది వృత్తిపరమైన వైద్య సలహాకు ప్రత్యామ్నాయం కాదు. తీవ్రమైన లక్షణాల కోసం ఎల్లప్పుడూ వైద్యుడిని సంప్రదించండి.',
      greeting: 'నమస్తే! నేను ఆరోగ్య సాథీ, మీ ఆరోగ్య సహాయకుడు. ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?',
      typeOrSpeak: 'మీ లక్షణాలను టైప్ చేయండి లేదా మాట్లాడండి...',
      analyzing: 'విశ్లేషిస్తోంది',
      urgentAttention: 'అత్యవసర దృష్టి అవసరం',
      seekImmediateHelp: 'దయచేసి సమీపంలోని ఆరోగ్య కేంద్రంలో వెంటనే వైద్య సహాయం పొందండి లేదా అత్యవసర సేవలకు కాల్ చేయండి.',
      nearbyHealthCenters: 'సమీపంలోని ఆరోగ్య కేంద్రాలు',
      distance: 'దూరం',
      call: 'కాల్ చేయండి',
      getDirections: 'దిశలను పొందండి',
    },
    bn: {
      tagline: 'আপনার স্বাস্থ্য সঙ্গী',
      selectLanguage: 'ভাষা নির্বাচন করুন',
      symptomCheck: 'উপসর্গ পরীক্ষা করুন',
      symptomCheckDesc: 'আপনার উপসর্গগুলি বর্ণনা করুন এবং নির্দেশনা পান',
      findPHC: 'স্বাস্থ্য কেন্দ্র খুঁজুন',
      findPHCDesc: 'কাছাকাছি স্বাস্থ্যসেবা সুবিধা সনাক্ত করুন',
      emergencyHelp: 'জরুরি সাহায্য',
      emergencyHelpDesc: 'জরুরি সেবায় দ্রুত প্রবেশ',
      disclaimer: '⚠️ এটি পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়। গুরুতর লক্ষণগুলির জন্য সর্বদা একজন ডাক্তারের সাথে পরামর্শ করুন।',
      greeting: 'নমস্কার! আমি আরোগ্য সাথী, আপনার স্বাস্থ্য সঙ্গী। আজ আমি কিভাবে আপনাকে সাহায্য করতে পারি?',
      typeOrSpeak: 'আপনার উপসর্গ টাইপ করুন বা বলুন...',
      analyzing: 'বিশ্লেষণ করছে',
      urgentAttention: 'জরুরি মনোযোগ প্রয়োজন',
      seekImmediateHelp: 'অনুগ্রহ করে নিকটতম স্বাস্থ্য কেন্দ্রে অবিলম্বে চিকিৎসা সহায়তা নিন বা জরুরি সেবায় কল করুন।',
      nearbyHealthCenters: 'কাছাকাছি স্বাস্থ্য কেন্দ্র',
      distance: 'দূরত্ব',
      call: 'কল করুন',
      getDirections: 'দিকনির্দেশনা পান',
    },
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};
